apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-ydr6
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0027-tenant/tkrw-pr712-0075-0027-app/devfile-sample-ydr6@sha256:af70e0c07baf0224e8eb7dfa96ce995fa0bf4883c67549b73479db7928691a32
        name: my-nodejs
        resources: {}
status: {}
